export const SET_SIMPSONS_API = "SET_SIMPSONS_API";
export const REMOVE_CHARACTER = "REMOVE_SIMPSON";
export const SET_LIKED_CHARACTER = "SET_LIKED_CHARACTER";
export const SET_USER_INPUT = "SET_USER_INPUT";
export const ADD_CHARACTER =  "ADD_CHARACTER";
export const SET_SCREEN_MODE = "SET_SCREEN_MODE"
export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT"
export const SORT_INPUT = "SORT_INPUT"